services:
    currency_exchange.currency_rates_yahoo:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\Provider\CurrencyRatesYahoo
        arguments: [ '@currency_exchange.currency_rates' ]
        tags:
                    -  { name: exchange.rate.provider }

    currency_exchange.currency_rates_google:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\Provider\CurrencyRatesGoogle
        arguments: [ '@currency_exchange.currency_rates' ]
        tags:
                    -  { name: exchange.rate.provider }

    currency_exchange.currency_rates:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\CurrencyRates
        arguments: [ "@doctrine.orm.entity_manager" ]

    exchange_rate_providers_collection:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\ExchangeRateProvidersCollection

    currency_exchange.rates:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Command\CurrencyRatesCommand
        arguments: [ '@exchange_rate_providers_collection' ]
        tags:
                    -  { name: console.command }

    currency_exchange.rate_best:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Command\CurrencyRateBestCommand
        arguments: [ '@exchange_rate_providers_collection' ]
        tags:
                    -  { name: console.command }

