services:
    currency_exchange.currency_rates_yahoo:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\Provider\CurrencyRatesYahoo
        arguments: [ '@currency_exchange.currency_rates' ]

    currency_exchange.currency_rates:
        class:  SauliusVaitkevicius\Bundle\CurrencyExchangeBundle\Service\CurrencyRates
        arguments: [ "@doctrine.orm.entity_manager" ]
